server:
  port: 8499

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: 192.168.232.130:1111
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.168.232.130:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      #sentinel持久化配置
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.232.130:1111
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'





